//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Task_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "This Field Musn't Be Empty")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This Field Musn't Be Empty")]
        public int ProductNumber { get; set; }

        [Required(ErrorMessage = "This Field Musn't Be Empty")]
        public string Color { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [Required(ErrorMessage = "This Field Musn't Be Empty")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "This Field Musn't Be Empty")]
        public int Weight { get; set; }
    }
}
