//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azure_Task_2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class UserChanx
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string OperationType { get; set; }
        public string Values { get; set; }
    }
}
